# Generated by Django 2.2.13 on 2020-06-23 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0002_auto_20200623_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='posted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.CharField(default='hello', max_length=25),
            preserve_default=False,
        ),
    ]
