# Generated by Django 2.2.13 on 2020-06-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0003_auto_20200623_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('user', models.CharField(max_length=25)),
                ('posted_time', models.DateTimeField()),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
