# Generated by Django 2.2.13 on 2020-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0004_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('user', models.CharField(max_length=25)),
                ('posted_time', models.DateTimeField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
