# Generated by Django 2.2.13 on 2020-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('answer_id', models.IntegerField()),
                ('like_status', models.CharField(max_length=10)),
            ],
        ),
    ]
