# Generated by Django 2.2.13 on 2020-07-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_status',
        ),
    ]
