# Generated by Django 2.2.13 on 2020-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0007_remove_like_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
