# Generated by Django 2.2.13 on 2020-07-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0009_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('QorA', models.CharField(max_length=10)),
                ('report_type', models.CharField(max_length=20)),
                ('QorA_id', models.IntegerField()),
            ],
        ),
    ]
