# Generated by Django 2.2.13 on 2020-07-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0010_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
    ]
