# Generated by Django 2.2.13 on 2020-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0011_remove_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='report',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='report',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
