# Generated by Django 2.2.13 on 2020-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_forum', '0015_auto_20200725_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='name',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='name',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
    ]
