# Generated by Django 2.2.13 on 2020-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_model',
            name='description',
        ),
        migrations.AlterField(
            model_name='news_model',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='published_at',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='url_to_image',
            field=models.URLField(blank=True),
        ),
    ]
