# Generated by Django 2.2.13 on 2020-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='body',
            field=models.TextField(),
        ),
    ]
