# Generated by Django 2.2.13 on 2020-07-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_auto_20200719_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='body',
            new_name='Eligible_for',
        ),
        migrations.AddField(
            model_name='scheme',
            name='Fiscal_incentives',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='Headed_by',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='Industry_applicable',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='Launched_in',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='Overview',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='Time_period',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='more_info_link',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
