# Generated by Django 2.2.13 on 2020-07-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_auto_20200722_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='Eligible_for',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Fiscal_incentives',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Headed_by',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Industry_applicable',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Launched_in',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Overview',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Time_period',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='head',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='more_info_link',
            field=models.URLField(default='N/A'),
        ),
    ]
