# Generated by Django 2.2.13 on 2020-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_auto_20200722_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='Eligible_for',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Fiscal_incentives',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Headed_by',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Industry_applicable',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Launched_in',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='Time_period',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='head',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='more_info_link',
            field=models.URLField(blank=True),
        ),
    ]
