# Generated by Django 2.2.8 on 2020-04-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='req',
        ),
    ]
