# Generated by Django 2.2.8 on 2020-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentee_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=25)),
                ('field', models.CharField(max_length=100)),
                ('sub_field', models.CharField(max_length=100)),
                ('startup', models.CharField(max_length=25)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_description', models.CharField(blank=True, max_length=250)),
                ('otp', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='mentor_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=25)),
                ('field', models.CharField(max_length=100)),
                ('sub_field', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('u_id', models.IntegerField()),
            ],
        ),
    ]
