# Generated by Django 2.2.8 on 2020-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0002_auto_20200420_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee_model',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor_model',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
