# Generated by Django 2.2.8 on 2020-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0003_auto_20200420_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee_model',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor_model',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
