# Generated by Django 2.2.8 on 2020-04-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_signup', '0005_auto_20200421_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('expired', 'expired')], default='pending', max_length=30)),
                ('requ_date', models.DateTimeField(auto_now_add=True)),
                ('repl_date', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('pay', models.PositiveIntegerField()),
                ('mentee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.mentee_model')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.mentor_model')),
            ],
        ),
    ]
