# Generated by Django 2.2.13 on 2020-07-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee_request_model',
            name='mentee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
