# Generated by Django 2.2.13 on 2020-07-30 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_mentee_request_model_mentee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee_request_model',
            name='request_posted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
