# Generated by Django 2.2.13 on 2020-07-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0005_auto_20200421_1533'),
        ('request', '0003_mentee_request_model_request_posted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee_request_model',
            name='mentor_id',
        ),
        migrations.AddField(
            model_name='mentee_request_model',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_signup.mentor_model'),
            preserve_default=False,
        ),
    ]
