# Generated by Django 2.2.13 on 2020-07-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_mentor_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_request_model',
            name='mentor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
