# Generated by Django 2.2.13 on 2020-07-31 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0005_auto_20200421_1533'),
        ('request', '0007_mentor_request_model_mentor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentor_mentee_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.mentee_model')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.mentor_model')),
            ],
        ),
    ]
