# Generated by Django 2.2.13 on 2020-07-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_mentor_mentee_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor_request_model',
            old_name='request',
            new_name='mentee_request',
        ),
    ]
