# Generated by Django 2.2.13 on 2020-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20200731_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee_request_model',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
