# Generated by Django 2.2.13 on 2020-07-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_mentee_request_model_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee_request_model',
            name='amount',
        ),
    ]
