# Generated by Django 2.2.13 on 2020-07-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_remove_mentee_request_model_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee_request_model',
            name='from_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mentee_request_model',
            name='to_time',
            field=models.CharField(max_length=20),
        ),
    ]
